### ISSUE TITLE
Is the pkg-config file misplaced?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/gobject-introspection-feedstock#63]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am trying to build libvips with meson + gobject-introspection but I feel like the file `gobject-introspection-1.0.pc` might be misplaced.

It is currently in the package `gobject-introspection` but maybe it should be in the `host-tools` or `libgirepository` package?

### Installed packages

```shell
.
```

### Environment info

```shell
1.74.0 build 1
```

**Comment by ryanvolz** [comment]
Maybe? We debated the placement of many things when the packages were split, but in reviewing the discussion in #47 I don't see the pkg-config file being one of those things.

I think the idea is that anyone using the library parts of this gobject-introspection will depend on the `gobject-introspection` output, which has the headers. To me that seems like the logical place for the pkg-config file as well since it points to a bunch of things that are only there when the full `gobject-introspection` package is installed, but I'd love to hear other arguments.

**Comment by hmaarrfk** [comment]
got it. I think there are some challenges in cross compiling (see libvips attempt)

I documented other challenges in
https://github.com/conda-forge/gobject-introspection-feedstock/issues/64
